### ISSUE TITLE
Time on Dev page

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#102] opened 2018-04-18 02:32 UTC
Date and Time should only be showing for a flash game. Flash game should be created and last for 3 hours.

Regular and friends games don't need to have the time as the game is created when they make it, not at a later date. The idea is to keep it simple  for businesses.

**Comment by anmolg** [comment] 2018-06-15 06:52
Duplicate of #104?

**Comment by EhJay22** [comment] 2018-06-15 15:38
Nope. The date and time on the dev-vendor page should only be there for the flash game so that the owner can select what time they want their flash game to start at. For the rest of the games it's  immediately / after that few minute window.

**Comment by anmolg** [comment] 2018-06-15 18:08
Can you please update the description. It still references end date and time option

**Comment by anmolg** [comment] 2018-06-15 18:09
If that functionality is needed, we will develop it once the core product is sorted out

**Comment by EhJay22** [comment] 2018-06-15 18:31
This has been something we've been asking about for 2 months now and it's been brought up multiple times. Do you have a timeline on when it will be working properly for businesses? Because as of next week the app is supposed to be on the App store.

**Comment by anmolg** [comment] 2018-06-15 20:01
This was a semi-duplicate of #124, hence this may have been missed when filtering out fields - since that issue was documenting all fields that should not be visible in various game types.

We always assumed that this was focused on the duration of the flash game. Now that it has been identified, we will work on it.

**Comment by EhJay22** [comment] 2018-06-15 20:05
Thank you!

**Closed** 2018-06-28 01:48 UTC
Labels: ready-for-testing, vendor-ui
